title: Will Yaworsky
author: Will Yaworsky
description: T-shaped developer who loves projects that use multiple technologies.
url: https://yaworsw.github.io
baseurl: ""

permalink: /blog/:title/

collections:
  projects:
    output: true
    permalink: /projects/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - docker-compose.yml
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ticket-house
  - .ticket-house.json
  - code
